config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  # root "posts#index"

  # UMD Customization
  root "shibboleth_login#home"

  get "initiate/:org_code" => "shibboleth_login#initiator", as: :initiator

  get "attributes" => "shibboleth_login#callback"

  get "hosting" => "shibboleth_login#hosting"

  # Reconfigure error routes to point to dynamic error pages
  match "/404", to: "errors#not_found", via: :all, as: :not_found
  match "/500", to: "errors#internal_server_error", via: :all, as: :server_error
  # End UMD Customization
end

app/controllers/shibboleth_login_controller.rb
class ShibbolethLoginController < ApplicationController
  def home
    organizations = Rails.configuration.shibboleth_config["organizations"]
    @org_list = organizations.values.sort_by { |v| v[:display_order] }
  end

  def initiator # rubocop:disable Metrics/MethodLength, Metrics/AbcSize
    org_code = params["org_code"]
    organizations = Rails.configuration.shibboleth_config["organizations"]
    sp_login_url = ENV["SP_LOGIN_URL"] || "/Shibboleth.sso/Login"
    callback_url = ENV["CALLBACK_URL"] || "/attributes"

    if organizations.key?(org_code.to_sym)
      org = organizations[org_code.to_sym]
      idp_entity_id = org[:idp_entity_id]
      session[:auth_org_code] = org_code
      url_encoded_idp_entity_id = ERB::Util.url_encode(idp_entity_id)
      url_with_callback = "#{sp_login_url}?entityID=#{url_encoded_idp_entity_id}&target=#{callback_url}"
      redirect_to url_with_callback
    else
      # Was not given a valid org_code, treat as 404 error
      redirect_to not_found_url
    end
  end

  def callback
    @env = request.env
    @params = request.params

    @name = @env["displayName"] || "#{@env["givenName"]} #{@env["sn"]}"
    @name = "N/A" if @name.strip.empty?
    @principal_name = @env["eduPersonPrincipalName"] || "N/A"
    @identifier = @env["eduPersonTargetedID"] || "N/A"
    @entitlement = @env["eduPersonEntitlement"] || "N/A"

    @user_authorized = user_authorized?(@entitlement)
  end

  def hosting
  end

  private

    # Returns true is the user is authorized, false otherwise.
    #
    # entitlement: the eduPersonEntitlement attribute from Shibboleth
    def user_authorized?(entitlement)
      expected_entitlement = "https://borrow.btaa.org/reciprocalborrower"
      entitlement.split(";").any? { |e| e.downcase == expected_entitlement }
    end
end

app/helpers/shibboleth_login_helper.rb
module ShibbolethLoginHelper
end

app/views/shibboleth_login/callback.html.erb
<% provide(:title, "User Attributes") %>

<div role="main" id="main-container" class="container">
  <div class="row">
    <div class="col-sm-12">
      <div class="row">
        <table class="table attributes">
          <tr>
            <th>Name:</th>
            <td><%= @name %></td>
          </tr>
          <tr>
            <th>Entitlement:</th>
            <td><%= @entitlement %></td>
          </tr>
          <tr>
            <th>Principal Name:</th>
            <td><%= @principal_name %></td>
          </tr>
          <tr>
            <th>Identifier:</th>
            <td><%= @identifier %></td>
          </tr>
        </table>

        <section id="authentication-message">
          <% if @user_authorized %>
            <p class="user-authorized">
              User is eligible for borrowing
            </p>
          <% else %>
            <p class="user-not-authorized">
              User is <strong>NOT</strong> eligible for borrowing due to missing "https://borrow.btaa.org/reciprocalborrower" in the eduPersonEntitlement.
            <p>
          <% end %>
          <p>
            For security purposes please close your browser to exit the system
          <p>
        </section>

        <% if Rails.env.development? || Rails.env.development_docker? %>
          <div class="panel panel-warning">
            <div class="panel-heading">

              <h2 class="panel-title">Debugging information (development only)</h2>
            </div>
            <div class="panel-body">
              <h3>Environment</h3>

              <ul>
                <% @env.each do |key, value| %>
                  <li><%= key %>: <%= value %></li>
                <% end %>
              </ul>

              <h3>Parameters</h3>

              <ul>
                <% @params.each do |key, value| %>
                  <li><%= key %>: <%= value %></li>
                <% end %>
              </ul>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/shibboleth_login/home.html.erb
<% provide(:title, "Welcome") %>

<div role="main" id="main-container" class="container">
  <div class="row">
    <div class="col-12">
      <div class="row">
        <div id='project-text'>
          <p>
          The institutions listed below agree to provide reciprocal borrowing
          privileges to current faculty, emeritus faculty, students, and staff
          at the other Big Ten Academic Alliance (BTAA) member libraries.
          Borrowing privileges are governed by the lending library based on
          local circulation policies established for guest borrowers. To make
          use of this service, borrowers must present an institutional photo ID
          and verify their current affiliation by authenticating through use of
          this BTAA Reciprocal Borrowing Application.
          </p>

          <p>
          To authenticate, please click on your home institution below and
          log-in using your institution user ID and password. A successful
          result will return your name, entitlement, and personal identifier
          number.
          </p>
        </div>

        <ul id="organization_list">
          <% @org_list.each do |org| %>
            <% org_code = org[:code] %>
            <% org_name = org[:name] %>

            <%= content_tag(:li, class: "", id: org_code + "_entry") do %>
                <%= link_to org_name, initiator_path(org_code: org_code) %>
            <% end %>
          <% end %>
        </ul>
      </div>
    </div>
  </div>
</div>

app/views/shibboleth_login/hosting.html.erb
<% provide(:title, "Hosting") %>

<div role="main" id="main-container" class="container">
  <div class="row">
    <div class="col-12">
      <div class="row">
        <h2>Hosting and Technology</h2>

        <p>The Reciprocal Borrowing application is built with the <a href="http://rubyonrails.org/">Ruby on Rails</a>
        web framework and <a href="https://shibboleth.net/">Shibboleth federated identity management</a> technologies.
        The source code is available at the GitHub <a
          href="https://github.com/umd-lib/reciprocal-borrowing">umd-lib/reciprocal-borrowing</a> repository. The
        application is built and hosted by the <a href="http://www.lib.umd.edu">University of Maryland Libraries</a> <a
          href="http://www.lib.umd.edu/dss">Digital Systems and Stewardship</a> division.</p>

        <ul>
          <li><a href="http://www.lib.umd.edu/about/privacy-info">Privacy Information</a></li>
          <li><a href="http://it.umd.edu/aup">Acceptable Use of IT Resources</a></li>
        </ul>
      </div>
    </div>
  </div>
</div>

app/views/shibboleth_login/initiator.html.erb
<h1>ShibbolethLogin#initiator</h1>
<p>Find me in app/views/shibboleth_login/initiator.html.erb</p>
<h2>Id: <%= @organization %>